# Generated by Django 3.1.1 on 2020-09-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Starship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('registry', models.CharField(max_length=50)),
                ('crew', models.IntegerField()),
            ],
        ),
    ]
